[package]
name = "skeleton"
version = "1.0.0"
description = "simple project"
authors = ["Solana Labs Maintainers <maintainers@solanalabs.com>"]
repository = "https://github.com/solana-labs/solana-program-library"
license = "Apache-2.0"
edition = "2021"

[features]
no-entrypoint = []
test-sbf = []

[dependencies]
arrayref = "0.3.7"
bincode = "1.3.3"
borsh = { version = "1.2.1", features = ["derive", "unstable__schema"] }
num-derive = "0.4"
num-traits = "0.2"
num_enum = "0.7.1"
solana-program = { version = "1.18.0", path = "/home/hana/work/solana/solana/sdk/program" }
thiserror = "1.0.52"

[dev-dependencies]
solana-program-test = { version = "1.18.0", path = "/home/hana/work/solana/solana/program-test" }
solana-sdk = { version = "1.18.0", path = "/home/hana/work/solana/solana/sdk" }
solana-vote-program = { version = "1.18.0", path = "/home/hana/work/solana/solana/programs/vote" }
test-case = "3.3"

[patch.crates-io]
solana-program = { path = "/home/hana/work/solana/solana/sdk/program" }
solana-sdk = { path = "/home/hana/work/solana/solana/sdk" }
solana-zk-token-sdk = { path = "/home/hana/work/solana/solana/zk-token-sdk" }

[lib]
crate-type = ["cdylib", "lib"]
